### ISSUE TITLE
瀑布流布局

### ISSUE THREAD

**Issue by wangyajundev** [wangyajundev/30-seconds-of-work#3]
### js实现瀑布流
> css:
```css
#waterFall {
    position: relative;
    margin: 0 auto;
}
.item {
    position: absolute;
    padding: 5px;
}
img {
    display: block;
    width: 200px;
    margin: 0 auto;
}
````

> html:
```html
<div id="waterFall">
    <div class="item"><img src="./img/1.jpg"></div>
    <div class="item"><img src="./img/2.jpg"></div>
    <div class="item"><img src="./img/3.jpg"></div>
    <div class="item"><img src="./img/4.jpg"></div>
    <div class="item"><img src="./img/5.jpg"></div>
    <div class="item"><img src="./img/6.jpg"></div>
    <div class="item"><img src="./img/7.jpg"></div>
    <div class="item"><img src="./img/8.jpg"></div>
    <div class="item"><img src="./img/9.jpg"></div>
    <div class="item"><img src="./img/10.jpg"></div>
</div>
````
> javascript:
```javascript
window.onload = function() {
    var gap = 0;
    var $waterFall = document.getElementById('waterFall'),
    $items = $waterFall.children;

    function getClient() {
        return {
            width: document.documentElement.clientWidth || document.body.clientWidth,
            height: document.documentElement.clientHeight || document.body.clientHeight
        }
    }
    
    function waterFall() {
        var itemWidth = $items[0].offsetWidth,
            cols = Math.floor(getClient().width / itemWidth);
        var heightArr = [];
        $waterFall.style.cssText = 'width:' + itemWidth * cols + 'px';
        for (var i = 0; i < $items.length; i++) {
            if (i < cols) { // 第一行
                $items[i].style.top = 0;
                $items[i].style.left = (itemWidth + gap) * i + 'px';
                heightArr.push($items[i].offsetHeight)
            } else {
                var minHeight = heightArr[0], index = 0; //最小高度 和 对应的索引
                for (let j = 0; j < $items.length; j++) {
                    if (minHeight > heightArr[j]) {
                        index = j;
                        minHeight = heightArr[j];
                    }
                }
                $items[i].style.top = heightArr[index] + gap + 'px';
                $items[i].style.left = $items[index].offsetLeft + 'px';
                // 重新计算最小列的高度 = 原有高度+新增高度+间隙高度
                heightArr[index] = heightArr[index] + $items[i].offsetHeight + gap;
            }
        }
    }

    waterFall();

    window.onresize = function() {
        waterFall();
    }

    window.onscroll = function() {
        var lastItemHeight = $items[$items.length - 1].offsetTop + Math.floor($items[$items.length - 1].offsetHeight) / 2
        var scrollTop = document.body.scrollTop || document.documentElement.scrollTop
        if (scrollTop + getClient().height > lastItemHeight) {
            var data = ['./img/11.jpg', './img/12.jpg', './img/13.jpg', './img/14.jpg', './img/15.jpg', './img/16.jpg', './img/17.jpg', './img/18.jpg', './img/19.jpg', './img/21.jpg'];
            for (var i = 0; i < data.length; i++) {
                var div = document.createElement('div');
                div.className = 'item';
                div.innerHTML = '<img src="' + data[i] + '" />';
                $waterFall.appendChild(div);
            }
            waterFall();
        }
    }
}
```

### 多列布局实现瀑布流

> css:
```css
#waterFall {
    column-width: 200px;
    /* column-count: 4; */
}
.item {
    /* padding: 5px; */
}
img {
    display: block;
    width: 200px;
    margin: 0 auto;
}
````
